import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  /*
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  */

  // Manual sidebar for our book
  bookSidebar: [
    {
      type: 'category',
      label: 'AI/Spec-Driven Book Creation + RAG Chatbot',
      items: [
        'chapter-1-introduction-to-physical-ai',
        'chapter-2-core-ai-system',
        'chapter-3-sensors-and-perceptions',
        'chapter-4-actuators-mechanical-system',
        'chapter-5-locomotion',
        'chapter-6-human-interaction',
        'chapter-7-applications',
        'chapter-8-future-trends',
        'intro', // Existing Docusaurus intro
      ],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
